### PR TITLE
Move everything to cms

### LINKED ISSUE #105: Merge partnerwebsite with cms
Why are there two applications, `partnerwebsite` and `cms`, inside this project?

We should consolidate into one called `webapp`, as with our other projects.

### PR DESCRIPTION
**Pull request by nottrobin**
The partnerwebsite app was pointless. I'm moving its settings etc. to the `cms` app. This shouldn't affect any functionality.

Fixes #105 

QA
---

``` bash
./run
```

Check the site and the admin area behave exactly as it used to.

### CODE REVIEW

**Comment by nottrobin** [comment]
As far as I'm concerned this only half solves the issue. I've filed #121 to solve the other half.

**Comment by nottrobin** [comment]
[Consolidate partnerwebsite app into the cms app](https://trello.com/c/FxEUfdqG/2949-consolidate-partnerwebsite-app-into-the-cms-app)

**Comment by WillMoggridge** [comment]
Sorry, I need to give up reviewing this for now as I need to do other stuff. It does not agree with my Docker, which is probably only a problem for me.

**Comment by nottrobin** [comment]
@willmoggridge k

**Pull request merged**
