### PR TITLE
Roll back to an older version of global.js to stop JS errors.

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Fixed the global.js to a previous version to stop errors.

## QA

- `./run`
- See that there are no JS errors when navigating the pages of the site.

### CODE REVIEW

**Comment by nottrobin** [comment]
:+1: LGTM

**Comment by anthonydillon** [comment]
Shouldn't this use the global-nav project?

**Comment by nottrobin** [comment]
@anthonydillon We're trying to fix an error on the production version of https://partners.ubuntu.com/find-a-partner, which is broken because https://assets.ubuntu.com/sites/ubuntu/latest/u/js/global.js has been pointed to a new version that doesn't work with Partners.

You're welcome to update this to use the global-nav project when you get back, but perhaps before you do, we really need to look at how it's using that (or any) latest links. This is precisely why I tend to be against the idea of linking to any "latest" versions of files.

**Comment by nottrobin** [comment]
When this goes live it will fix #130

**Pull request merged**
